name: build, test, and deploy docs to GitHub Pages

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cargo build
        run: cargo build
        
      - name: cargo test
        run: cargo test
        
  build-docs:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cargo doc 
        run: cargo doc --document-private-items --open --no-deps
 
      - name: deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: target/doc/interviewpuzzle # The folder the action should deploy.
